/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xE7, 0xE3, 0x14, 0x4D, 0x04, 0x11, 0x09, 0xEA}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }

#define VIAL_UNLOCK_COMBO_COLS { 0, 10 }

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

// The pin connected to the data pin of the LEDs
#define WS2812_DI_PIN B7

// The number of LEDs connected
#define RGB_MATRIX_LED_COUNT 10

#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
#define ENABLE_RGB_MATRIX_DUAL_BEACON
#define ENABLE_RGB_MATRIX_HUE_BREATHING
